### ISSUE TITLE
AppImage or Flatpak version

### ISSUE THREAD

**Issue by eadmaster** [FCare/Kronos#967]
please add an AppImage or a Flatpak build, the Ubuntu build in the releases section is not working in my distro due to missing dependencies.

**Comment by FCare** [comment]
I do not have enough time to implement this. You can propose pull requests, I will be very happy to integrate them :-)

**Comment by WingofaGriffin** [comment]
I tried creating a manifest for this, though I have been running into build errors:

```yaml
app-id: io.github.fcare.Kronos
runtime: org.kde.Platform
runtime-version: 5.15-22.08
sdk: org.kde.Sdk
command: kronos
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --filesystem=host
  - --device=dri
modules:  
  - name: kronos
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DUSE_QT5=ON
    subdir: yabause
    sources:
      - type: git
        url: https://github.com/FCare/Kronos.git
        tag: 2.3.1_official_release
        commit: 1b9819ceb8d8a2a2811fd20654c13ea6aa6d380c
```
From the errors I see, it looks like there are issues with glew/glu
`-- Could NOT find GLEW (missing: GLEW_INCLUDE_DIR GLEW_LIBRARY) `
`/run/build/kronos/yabause/src/tools/gllibs/include/GL/glew.h:1205:14: fatal error: GL/glu.h: No such file or directory`
`make[1]: *** [CMakeFiles/Makefile2:273: src/CMakeFiles/kronos.dir/all] Error 2`

I suspect this is because the glu/glew install from the [Flatpak KDE Runtime](https://invent.kde.org/packaging/flatpak-kde-runtime) is not being properly found by the build tool. I did check the pkg list, and it should be included on the version I provided, but I could very easily be wrong due to lack of experience with this. Using cmake-ninja instead seems to result in more errors.

Happy to make PRs to fix this, but will need to spend some time digging into the code to debug this. @FCare if you have any tips/clues, I'm all ears.
